View Registered Firearms
Linesmerrill/police-cad pull request #443
Opened 2021-05-08 05:08 UTC by Braeden57

This Update fixes a small bug in the civilian dashboard while registering a new firearm.
It also allows the police/dispatch dashboard to quickly search registered firearms from a Name Search Database

2021-05-08 14:52 UTC, Linesmerrill commented
Dude this is freakin legit!! ❤️

2021-05-08 15:48 UTC, Linesmerrill requested changes
Look good, just some minor grammar fixes

2021-05-08 15:48 UTC, Linesmerrill commented on views/dispatch-dashboard.ejs
> +                                                            Fireamrs
```suggestion
                                                            Firearms
```

2021-05-08 15:48 UTC, Linesmerrill commented on views/dispatch-dashboard.ejs
> +        // Check if firearm is stolen and appen result
```suggestion
        // Check if firearm is stolen and append result
```

2021-05-08 15:48 UTC, Linesmerrill commented on views/dispatch-dashboard.ejs
> +        `<div id="registered-firearms-panel-body-${index}" class="panel-body reg-arm">`
Let's add some style details to the weapon type text shown on the page. To do this we can simply just apply some style details to the `reg-arm` class in `styles.css`

File: `styles.css`:

Add:
```
.reg-arm {
    text-transform: capitalize;
}
```

Then it will appear on the page like this:
<img width="570" alt="Screen Shot 2021-05-08 at 8 41 04 AM" src="https://user-images.githubusercontent.com/15384983/117545265-dc141600-afd9-11eb-88f6-24552b927b8c.png">

2021-05-08 15:48 UTC, Linesmerrill commented on views/police-dashboard.ejs
> +                                                            Fireamrs
```suggestion
                                                            Firearms
```

2021-05-08 15:48 UTC, Linesmerrill commented on views/police-dashboard.ejs
> +        // Check if firearm is stolen and appen result
```suggestion
        // Check if firearm is stolen and append result
```

2021-05-08 18:28 UTC, Braeden57 commented on views/dispatch-dashboard.ejs
> +        `<div id="registered-firearms-panel-body-${index}" class="panel-body reg-arm">`
I tried the class solution for this. But to my surprise it didn't work. I tried different ways to fix it. But instead I just added it as a style inside the div rather than referencing the class.

2021-05-08 19:49 UTC, Linesmerrill commented
Found a bug with it not auto populating the drop down when clicking on a firearm. This should fix that problem: https://github.com/Linesmerrill/police-cad/pull/444

2021-05-08 20:13 UTC, Linesmerrill commented
I did encounter a bug. How to replicate:

1. Search a civ name either in the police-dashboard or dispatch-dashboard

![image](https://user-images.githubusercontent.com/15384983/117552128-800fb880-affe-11eb-9eee-2a8d7a388372.png)

2. Make sure they have registered firearms
3. Click on the new "Search Registered Firearms" button

![image](https://user-images.githubusercontent.com/15384983/117552166-ae8d9380-affe-11eb-8600-f11282084f97.png)

4. View how many results come back, for this example there are 2 registered firearms so we will see 2.

![image](https://user-images.githubusercontent.com/15384983/117552191-c533ea80-affe-11eb-8537-f2946664e977.png)

5. Click the 'X' to close out of the "Registered Firearms" modal
6. Click on the new "Search Registered Firearms" button again
7. See there are now 4 results coming back:

![image](https://user-images.githubusercontent.com/15384983/117552230-f01e3e80-affe-11eb-9079-b3d07af93be3.png)

8. This continues to double everytime "Search Registered Firearms" is clicked.

We should clear the list everytime before trying to append these to the div. We did something similar with the vehicles search button, so try looking at that for reference if you get stuck.

2021-05-10 01:30 UTC, Linesmerrill commented
ok this all looks good to me. Ill merge into our develop branch, add get all the release notes ready for an MR to master. Thanks @Braeden57 for the contribution! Amazing

2021-05-10 01:30 UTC, merged