Fire ems update
Linesmerrill/police-cad pull request #548
Opened 2021-12-01 01:44 UTC by SowinskiBraeden

-Adds the Ability for Dispatch to assign Fire/EMS to call
-New Call Classifier ie. Fire EMS Police
-EMS gets Side Navigation Bar
-Improved EMS Vehicle (Engine Number, List of Car Types)
- Fire/EMS Engine Status
- Dispatch See active Fire/EMS Engines
- Dispatch Change Fire/EMS Engines status

2021-12-04 20:08 UTC, Linesmerrill commented
Danng this looks good!! 
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/15384983/144723209-e5af1911-6c41-4934-9d55-53a491693766.png">

2021-12-05 19:08 UTC, Linesmerrill requested changes

2021-12-05 19:08 UTC, Linesmerrill commented on app/models/civilian.js
> +    deceased: String, // Shows in NameDB and MedicalDB as Deceased (yes/no)
suggestion: unless we plan to have more potential values for deceased ("yes" or "no") then I think we add this as a boolean value so we dont have to worry about text or casing.

So we could have 1 (true) as alive, and 0 (false) as dead. 

Let me know your thoughts on that.

2021-12-05 19:08 UTC, Linesmerrill commented on app/models/emsVehicle.js
> +        engineNumber: String, // Call sign for vehicle ex. Engine '31'
kudos: thanks for adding the help text here, I always forget what these mean later on. 👍

2021-12-05 19:08 UTC, Linesmerrill commented on app/routes.js
> +          return socket.emit('bot_updated_status', req);npm
```suggestion
          return socket.emit('bot_updated_status', req);
```

2021-12-05 19:13 UTC, SowinskiBraeden commented on app/models/civilian.js
> +    deceased: String, // Shows in NameDB and MedicalDB as Deceased (yes/no)
Sure I'll update that

2021-12-05 19:25 UTC, SowinskiBraeden commented on app/routes.js
> +          return socket.emit('bot_updated_status', req);npm
Removed that, my bad

2021-12-05 19:28 UTC, Linesmerrill commented on app/models/civilian.js
> +    deceased: String, // 1: no (alive), 0: yes (deceased)
```suggestion
    deceased: Boolean, // true: no (alive), false: yes (deceased)
```

2021-12-05 19:29 UTC, Linesmerrill commented on app/routes.js
> +          'civilian.deceased': 1
```suggestion
          'civilian.deceased': true
```

2021-12-05 19:32 UTC, Linesmerrill approved these changes

2021-12-05 19:34 UTC, Linesmerrill commented on app/routes.js
> +    if (req.body.deceased=="yes") {
```suggestion
    if (req.body.deceased) {
```

2021-12-05 19:35 UTC, Linesmerrill commented on app/routes.js
> +    if (req.body.deceased=="yes") {
Can we make this a boolean in the form? if not we can prob leave this as it

2021-12-05 19:36 UTC, Linesmerrill commented on app/models/civilian.js
> +  console.log(this.civilian.deceased);
```suggestion
```

2021-12-05 19:37 UTC, Linesmerrill commented on app/models/civilian.js
> +    this.civilian.deceased = "no"
```suggestion
    this.civilian.deceased = false
```

2021-12-05 19:38 UTC, Linesmerrill commented on app/models/civilian.js
> +    this.civilian.deceased = req.body.deceased.trim();
```suggestion
    this.civilian.deceased = req.body.deceased;
```

2021-12-07 22:32 UTC, Linesmerrill commented
1. Shut down the server
2. Restart server
3. Navigate to Fire/EMS page: http://localhost:8080/ems-dashboard
4. Click on a vehicle in the list
5. See attached screenshot

![image](https://user-images.githubusercontent.com/15384983/145116038-6caf8077-475b-45a4-961c-89b6c39fe39d.png)


It appears to be using the default values on startup, which should get updated after a socket update.

Expected Behavior: This loads the values from the database on initial page load, or shows as empty if values are not set.

2021-12-08 14:18 UTC, Linesmerrill requested changes

2021-12-08 14:18 UTC, Linesmerrill commented on views/ems-dashboard.ejs
> +                <label class="col-md-8" id="engineNumView">engine nymber here</label>
Two issues with this:

1) `nymber` -> `number`
2) https://github.com/Linesmerrill/police-cad/pull/548#issuecomment-988309376

2021-12-14 04:47 UTC, SowinskiBraeden commented
> ### Expected Behavior:
> Upon page load, the user can click on any of the vehicles and it will show either the accurate values from the database, or empty if the values have not been set.
> 
> ### How to recreate the bug:
> 1. Shut down the server
> 2. Restart server
> 3. Navigate to Fire/EMS page: http://localhost:8080/ems-dashboard
> 4. Click on a vehicle in the list
> 5. See attached screenshot
> 
> ![image](https://user-images.githubusercontent.com/15384983/145116038-6caf8077-475b-45a4-961c-89b6c39fe39d.png)
> 
> ### Conclusion
> It appears to be using the default values on startup, which should get updated after a socket update.

This appears to only affect the `Status` related values, should be an easy fix

2021-12-18 15:13 UTC, Linesmerrill requested changes

2021-12-18 15:13 UTC, Linesmerrill commented on views/ems-dashboard.ejs
> +    console.log(status)
```suggestion
```

2021-12-18 16:54 UTC, Linesmerrill requested changes

2021-12-18 16:54 UTC, Linesmerrill commented on views/ems-dashboard.ejs
> +            <% if (calls !=null && calls.length> 0) { %>
Shoot found another issue:

## Expected Behavior

A user that is not in a community can load the Fire/Ems dashboard page without an error

## Actual Behavior

Application crashes and throws this error:

```ReferenceError: police-cad/views/ems-dashboard.ejs:207
    205|             <h4>Assigned Calls: </h4>
    206|             <h5>Click for details</h5>
 >> 207|             <% if (calls !=null && calls.length> 0) { %>
    208|               <% for(var i=0; i<calls.length; i++) { %>
    209|                 <% if (calls[i].call.status==true) { %>
    210|                   <% if (calls[i].call.assignedFireEms !=null && calls[i].call.assignedFireEms !='' ) { %>

calls is not defined
    at eval (police-cad/views/ems-dashboard.ejs:98:8)
    at ems-dashboard (police-cad/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (police-cad/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (police-cad/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (police-cad/node_modules/express/lib/view.js:135:8)
    at tryRender (police-cad/node_modules/express/lib/application.js:640:10)
    at Function.render (police-cad/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (police-cad/node_modules/express/lib/response.js:1012:7)
    at police-cad/app/routes.js:353:24
    at police-cad/node_modules/mongoose/lib/model.js:5074:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

## How to recreate

1. Create a new account that is not in a community
2. Try to access the Fire/EMS dashboard
3. See above error

## Possible Conclusion

It appears that in `routes.js` if the user is not in a community we do not pass the `calls` object to the html page. This will cause a panic and throw the above error. To prevent this we can simply pass that object a `null` in the router, something like this should suffice:

```
return res.render('ems-dashboard', {
              user: req.user,
              personas: dbPersonas,
              vehicles: dbVehicles,
              communities: dbCommunities,
              calls: null,
              context: context
            });
```

2021-12-18 18:49 UTC, SowinskiBraeden commented on views/ems-dashboard.ejs
> +            <% if (calls !=null && calls.length> 0) { %>
Updated that

2021-12-19 15:28 UTC, Linesmerrill commented on app/routes.js
> +                  dbEmsEngines: dbEmsEngines,
issue: you will want to add the corresponding value for the non community route as well. 

```
return res.render('dispatch-dashboard', {
            user: req.user,
            vehicles: null,
            civilians: null,
            firearms: null,
            tickets: null,
            arrestReports: null,
            warrants: null,
            dbEmsEngines: null,
            communities: dbCommunities,
            bolos: dbBolos,
            commUsers: null,
            calls: null,
            context: context
          });
```

2021-12-19 19:51 UTC, SowinskiBraeden commented on app/routes.js
> +                  dbEmsEngines: dbEmsEngines,
Got that covered

2021-12-27 04:10 UTC, Linesmerrill requested changes

2021-12-27 04:10 UTC, Linesmerrill commented on app/routes.js
>            });
Got a couple updates we can add into your MR here: https://github.com/Linesmerrill/police-cad/pull/554

2021-12-27 16:30 UTC, Linesmerrill approved these changes

2021-12-31 20:09 UTC, Linesmerrill commented
https://github.com/Linesmerrill/police-cad/pull/566#issuecomment-1003442530

2022-01-09 23:22 UTC, Linesmerrill commented
Only things I think we should add to this is a socket receiver on the ems-dashboard page for when a call is assigned/updated/closed. This way they dont have to refresh their page when a new call comes in or is updated/closed.

After that we should be good to merge this

2022-01-09 23:29 UTC, SowinskiBraeden commented
> Only things I think we should add to this is a socket receiver on the ems-dashboard page for when a call is assigned/updated/closed. This way they dont have to refresh their page when a new call comes in or is updated/closed.
> 
> After that we should be good to merge this
> 
> ![image](https://user-images.githubusercontent.com/15384983/148705369-a598ab51-c9a6-4ada-bf11-ae843c8c4a87.png)

Yeah sure, Ill work on that

2022-01-11 23:34 UTC, Linesmerrill approved these changes

2022-01-11 23:34 UTC, merged